### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by fawaf**
so one can build the packages directly in the repo

### CODE REVIEW

**Comment by fawaf** [comment]
Poke @michel-stam

**Comment by michel-stam** [comment]
Hi @fawaf ,

Sorry for some reason I had not noticed this. Can you tell me exactly under what circumstances packages end up in the ripe-atlas-software-probe directory? rpm build creates its own directory structure, does this relate to Debian?

Cheers,

Michel

**Comment by fawaf** [comment]
Basically yep. Or any arch/os that the provided rpms do not support.

**Comment by michel-stam** [comment]
Alright I will merge it into the development branch, you'll see it on the next release :)

**Pull request closed without merging**
